CREATE TABLE MEMBER(
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(128) NOT NULL,
  EMAIL VARCHAR2(256) NOT NULL UNIQUE,
  AGE NUMBER
);

CREATE SEQUENCE mem_seq
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  NOCACHE
  NOORDER
;

CREATE TABLE ARTICLE(
  ID NUMBER,
  TITLE VARCHAR2(256),
  DESCRIPTION VARCHAR2(1000),
  CREATED DATE,
  UPDATED DATE,
  MEMBER_ID NUMBER,
  FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE CASCADE
);

CREATE SEQUENCE article_seq
  INCREMENT BY 1
  START WITH 1
  NOCACHE
  NOCYCLE
  NOORDER;