
INSERT INTO users (username, password, enabled)
VALUES ('user', '$2a$12$VetWbD.gzXI715kIkztdNOD0n18NMq01NCD9UjN5hNdeClI4SZY2a', true);

INSERT INTO USERS(USERNAME, PASSWORD, ENABLED)
  VALUES('admin', '$2a$12$VetWbD.gzXI715kIkztdNOD0n18NMq01NCD9UjN5hNdeClI4SZY2a', true);

INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('user', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY)
VALUES('admin', 'ROLE_ADMIN');